apiVersion: v1
kind: ConfigMap
metadata:
  name: restovyn-config
  namespace: restovyn-system
  labels:
    app.kubernetes.io/name: restovyn
data:
  NODE_ENV: "production"
  PORT: "4000"
  ADMIN_PORT: "3000"
  POSTGRES_DB: "restovyn_db"
  POSTGRES_HOST: "pgbouncer.restovyn-system.svc.cluster.local"
  POSTGRES_PORT: "6432"
  REDIS_HOST: "redis.restovyn-system.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_URL: "redis://redis.restovyn-system.svc.cluster.local:6379"
  LOG_LEVEL: "info"
  CORS_ORIGIN: "*"
  NEXT_PUBLIC_API_URL: "https://pos.restovyn.internal/api/v1"
  NEXT_PUBLIC_WS_URL: "wss://pos.restovyn.internal"
