apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: restovyn-ingress
  namespace: restovyn-system
  labels:
    app.kubernetes.io/name: restovyn
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "86400"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "86400"
    nginx.ingress.kubernetes.io/websocket-services: "api"
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Frame-Options: SAMEORIGIN";
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "X-XSS-Protection: 1; mode=block";
spec:
  tls:
    - hosts:
        - pos.restovyn.internal
        - admin.restovyn.internal
      secretName: restovyn-tls-cert
  rules:
    - host: pos.restovyn.internal
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 4000
          - path: /socket.io
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 4000
    - host: admin.restovyn.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: admin-web
                port:
                  number: 3000
