apiVersion: v1
kind: Namespace
metadata:
  name: restovyn-system
  labels:
    app.kubernetes.io/name: restovyn
    app.kubernetes.io/part-of: restovyn-platform
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: restovyn-quota
  namespace: restovyn-system
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "30"
