apiVersion: v1
kind: Secret
metadata:
  name: restovyn-secrets
  namespace: restovyn-system
  labels:
    app.kubernetes.io/name: restovyn
type: Opaque
stringData:
  POSTGRES_USER: "restovyn"
  POSTGRES_PASSWORD: "change_me_super_secure_postgres_pass"
  POSTGRES_READONLY_PASSWORD: "change_me_readonly_pass"
  DATABASE_URL: "postgresql://restovyn:change_me_super_secure_postgres_pass@pgbouncer.restovyn-system.svc.cluster.local:6432/restovyn_db?schema=public&pgbouncer=true"
  JWT_SECRET: "change_me_min_32_characters_super_secret_jwt_key_here"
  JWT_REFRESH_SECRET: "change_me_min_32_characters_super_secret_jwt_refresh_key"
