export enum StaffRole {
  OWNER = "OWNER",
  MANAGER = "MANAGER",
  CASHIER = "CASHIER",
  CAPTAIN = "CAPTAIN",
  KITCHEN = "KITCHEN",
  INVENTORY_MANAGER = "INVENTORY_MANAGER",
  ACCOUNTANT = "ACCOUNTANT",
}

export enum StaffStatus {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
  SUSPENDED = "SUSPENDED",
}

export enum TableStatus {
  AVAILABLE = "AVAILABLE",
  OCCUPIED = "OCCUPIED",
  RESERVED = "RESERVED",
  BILL_REQUESTED = "BILL_REQUESTED",
  CLEANING = "CLEANING",
  OUT_OF_SERVICE = "OUT_OF_SERVICE",
}

export enum OrderType {
  DINE_IN = "DINE_IN",
  TAKEAWAY = "TAKEAWAY",
  DELIVERY = "DELIVERY",
}

export enum OrderSource {
  POS = "POS",
  CAPTAIN = "CAPTAIN",
  MANAGER = "MANAGER",
  PHONE = "PHONE",
  OTHER = "OTHER",
}

export enum OrderStatus {
  DRAFT = "DRAFT",
  CONFIRMED = "CONFIRMED",
  KOT_CREATED = "KOT_CREATED",
  PREPARING = "PREPARING",
  READY = "READY",
  SERVED = "SERVED",
  BILL_REQUESTED = "BILL_REQUESTED",
  BILLED = "BILLED",
  PAID = "PAID",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
}

export enum KOTStatus {
  NEW = "NEW",
  ACCEPTED = "ACCEPTED",
  PREPARING = "PREPARING",
  READY = "READY",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
}

export enum PriorityLevel {
  NORMAL = "NORMAL",
  HIGH = "HIGH",
  URGENT = "URGENT",
}

export enum PaymentMethod {
  CASH = "CASH",
  CARD = "CARD",
  UPI = "UPI",
  ONLINE = "ONLINE",
  WALLET = "WALLET",
  OTHER = "OTHER",
}

export enum PaymentStatus {
  PENDING = "PENDING",
  SUCCESS = "SUCCESS",
  FAILED = "FAILED",
  REFUNDED = "REFUNDED",
  PARTIALLY_REFUNDED = "PARTIALLY_REFUNDED",
  VOIDED = "VOIDED",
}

export enum RefundType {
  FULL = "FULL",
  PARTIAL = "PARTIAL",
  ITEM = "ITEM",
}

export enum StockMovementType {
  PURCHASE = "PURCHASE",
  SALE_CONSUMPTION = "SALE_CONSUMPTION",
  WASTAGE = "WASTAGE",
  ADJUSTMENT = "ADJUSTMENT",
  RETURN = "RETURN",
  TRANSFER = "TRANSFER",
  OPENING_STOCK = "OPENING_STOCK",
}

export enum WastageReason {
  EXPIRED = "EXPIRED",
  BURNT = "BURNT",
  DAMAGED = "DAMAGED",
  SPILLAGE = "SPILLAGE",
  OVERPRODUCTION = "OVERPRODUCTION",
  OTHER = "OTHER",
}

export enum LoyaltyTxType {
  EARN = "EARN",
  REDEEM = "REDEEM",
  EXPIRE = "EXPIRE",
  ADJUSTMENT = "ADJUSTMENT",
}

export enum SyncStatus {
  PENDING = "PENDING",
  APPLIED = "APPLIED",
  CONFLICT = "CONFLICT",
  FAILED = "FAILED",
}

export enum RealtimeEvent {
  ORDER_CREATED = "ORDER_CREATED",
  ORDER_UPDATED = "ORDER_UPDATED",
  ORDER_CANCELLED = "ORDER_CANCELLED",
  KOT_CREATED = "KOT_CREATED",
  KOT_UPDATED = "KOT_UPDATED",
  KOT_READY = "KOT_READY",
  TABLE_UPDATED = "TABLE_UPDATED",
  PAYMENT_UPDATED = "PAYMENT_UPDATED",
  BILL_REQUESTED = "BILL_REQUESTED",
  MENU_UPDATED = "MENU_UPDATED",
  STOCK_UPDATED = "STOCK_UPDATED",
}
